# Check `LC_CTYPE=en_US.UTF-8` if you have issue with full width characters.

font_family		    JetBrainsMono NFM
bold_font		    JetBrainsMono NFM Bold
italic_font		    JetBrainsMono NFM Italic
bold_italic_font	JetBrainsMono NFM Bold Italic
font_size		    14.0
force_ltr		    no

tab_bar_edge		bottom

